import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/sections/Footer";

const font = Noto_Serif({
  variable: "--font-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased min-h-screen overflow-x-hidden`}
      >
        <Navbar />
        <main className="mt-[64.89px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
