export interface Theme {
  name: string;
  colors: Record<string, string>;
}

export const themes: Theme[] = [
  {
    name: "Light",
    colors: {
      primary: "#FF7D29",
      "primary-foreground": "#ffffff",
      secondary: "#c5682b",
      "secondary-foreground": "#ffffff",
      muted: "#fffde7",
      "muted-foreground": "#000",
      background: "#c5692b63",
      foreground: "#1f1f1f",
      card: "#7B4019",
      "card-foreground": "#FFEEA9",
    },
  },
  {
    name: "Blue-ish",
    colors: {
      primary: "#3338A0",
      "primary-foreground": "#ffffff",
      secondary: "#1c217f",
      "secondary-foreground": "#ffffff",
      muted: "#fffde7",
      "muted-foreground": "#000",
      background: "#eaeaea",
      foreground: "#000",
      card: "#0f172b",
      "card-foreground": "#ffffff",
      navbar: "#3338a04c",
    },
  },
  {
    name: "theme3",
    colors: {
      primary: "#3338A0",
      "primary-foreground": "#ffffff",
      secondary: "#1c217f",
      "secondary-foreground": "#ffffff",
      muted: "#fffde7",
      "muted-foreground": "#000",
      background: "#0c0e26",
      foreground: "#cdcff3",
      card: "#2a2b33",
      "card-foreground": "#ffffff",
      navbar: "#3338a04c",
    },
  },
  {
    name: "theme4",
    colors: {
      primary: "#5F8D4E",
      "primary-foreground": "#ffffff",
      secondary: "#285430",
      "secondary-foreground": "#ffffff",
      background: "#E5D9B6",
      foreground: "#000",
    },
  },

  // Append these to your existing `themes` array
  {
    name: "Kenroz",
    colors: {
      primary: "#df2a33",
      "primary-foreground": "#ffffff",
      secondary: "#9B2730",
      "secondary-foreground": "#ffffff",
      muted: "#fffde7",
      "muted-foreground": "#7a1c22",
      background: "#fff8ec",
      foreground: "#1f1f1f",
      card: "#fff1f2",
      "card-foreground": "#861b1b",
      navbar: "#df2a3340",
    },
  },
  {
    name: "Lavender Dream",
    colors: {
      primary: "#7C3AED",
      "primary-foreground": "#ffffff",
      secondary: "#A78BFA",
      "secondary-foreground": "#1b1035",
      muted: "#EDE9FE",
      "muted-foreground": "#3B2B63",
      background: "#F5F3FF",
      foreground: "#1F1636",
      card: "#2E1065",
      "card-foreground": "#F5F3FF",
      navbar: "#7C3AED40",
    },
  },
  {
    name: "Teal Breeze",
    colors: {
      primary: "#0D9488",
      "primary-foreground": "#ffffff",
      secondary: "#14B8A6",
      "secondary-foreground": "#062725",
      muted: "#CCFBF1",
      "muted-foreground": "#0B3B36",
      background: "#F0FDFA",
      foreground: "#072724",
      card: "#134E4A",
      "card-foreground": "#D1FAE5",
      navbar: "#0D948840",
    },
  },
  {
    name: "Sunset Pop",
    colors: {
      primary: "#F97316",
      "primary-foreground": "#111111",
      secondary: "#DB2777",
      "secondary-foreground": "#ffffff",
      muted: "#FED7AA",
      "muted-foreground": "#7C2D12",
      background: "#FFF7ED",
      foreground: "#1A120B",
      card: "#7C2D12",
      "card-foreground": "#FFE8D6",
      navbar: "#F9731640",
    },
  },
  {
    name: "Aqua Neon",
    colors: {
      primary: "#06B6D4",
      "primary-foreground": "#06202A",
      secondary: "#3B82F6",
      "secondary-foreground": "#ffffff",
      muted: "#E0F2FE",
      "muted-foreground": "#0F2B3A",
      background: "#F0F9FF",
      foreground: "#0B1320",
      card: "#082F49",
      "card-foreground": "#E0F2FE",
      navbar: "#06B6D440",
    },
  },
  {
    name: "Emerald Noir",
    colors: {
      primary: "#22C55E",
      "primary-foreground": "#071F12",
      secondary: "#84CC16",
      "secondary-foreground": "#081402",
      muted: "#0F172A",
      "muted-foreground": "#94A3B8",
      background: "#0B0F10",
      foreground: "#E5F6ED",
      card: "#111827",
      "card-foreground": "#D1FAE5",
      navbar: "#22C55E33",
    },
  },
  {
    name: "Royal Gold",
    colors: {
      primary: "#C28A0F",
      "primary-foreground": "#140A00",
      secondary: "#2D1B69",
      "secondary-foreground": "#ffffff",
      muted: "#F5E7C1",
      "muted-foreground": "#4B3A0E",
      background: "#FFF8E1",
      foreground: "#1B0A2A",
      card: "#3B2F0B",
      "card-foreground": "#FDE68A",
      navbar: "#C28A0F40",
    },
  },
  {
    name: "Berry Crush",
    colors: {
      primary: "#E11D48",
      "primary-foreground": "#ffffff",
      secondary: "#7C3AED",
      "secondary-foreground": "#ffffff",
      muted: "#FBCFE8",
      "muted-foreground": "#9D174D",
      background: "#FFF1F2",
      foreground: "#2B0B16",
      card: "#500724",
      "card-foreground": "#FFE4E6",
      navbar: "#E11D4840",
    },
  },
  {
    name: "Marshmallow Mint",
    colors: {
      primary: "#10B981",
      "primary-foreground": "#06281E",
      secondary: "#F472B6",
      "secondary-foreground": "#3A0A22",
      muted: "#E8FDF5",
      "muted-foreground": "#065F46",
      background: "#F0FDF4",
      foreground: "#0F172A",
      card: "#FFFFFF",
      "card-foreground": "#0F172A",
      navbar: "#10B98133",
    },
  },
  {
    name: "Midnight Plum",
    colors: {
      primary: "#A855F7",
      "primary-foreground": "#1A0B2A",
      secondary: "#F59E0B",
      "secondary-foreground": "#1A1302",
      muted: "#1E293B",
      "muted-foreground": "#94A3B8",
      background: "#0B1020",
      foreground: "#EDE9FE",
      card: "#18122B",
      "card-foreground": "#F5F3FF",
      navbar: "#A855F733",
    },
  },
  {
    name: "Cyber Lime",
    colors: {
      primary: "#A3E635",
      "primary-foreground": "#0F1A00",
      secondary: "#22D3EE",
      "secondary-foreground": "#00141A",
      muted: "#1F2937",
      "muted-foreground": "#9CA3AF",
      background: "#0B0B0E",
      foreground: "#E6FBD5",
      card: "#111317",
      "card-foreground": "#ECFCCB",
      navbar: "#A3E63533",
    },
  },
  {
    name: "Copper Teal",
    colors: {
      primary: "#B45309",
      "primary-foreground": "#FFF5E6",
      secondary: "#0EA5A6",
      "secondary-foreground": "#042B2B",
      muted: "#FDE68A",
      "muted-foreground": "#7A4E0A",
      background: "#FFF7ED",
      foreground: "#1B1309",
      card: "#0F766E",
      "card-foreground": "#E0F2F1",
      navbar: "#B4530933",
    },
  },
];
